CREATE TABLE "mytable" (
  "------------------query 1-------------------------------------" text
);

INSERT INTO "mytable" ("------------------query 1-------------------------------------")
VALUES
('SELECT'),
('c.CustomerId'),
('c.FirstName'),
('c.LastName'),
('i.InvoiceId'),
('i.InvoiceDate'),
('i.Total'),
('FROM Customer c'),
('INNER JOIN Invoice i'),
('ON c.CustomerId = i.CustomerId;'),
('------------------------------query 2------------------------'),
('SELECT'),
('c.CustomerId'),
('c.FirstName'),
('c.LastName'),
('FROM Customer c'),
('LEFT JOIN Invoice i'),
('ON c.CustomerId = i.CustomerId'),
('WHERE i.InvoiceId IS NULL;'),
('--------------------------query 3---------------------------'),
('SELECT'),
('t.Name AS Product'),
('SUM(il.UnitPrice * il.Quantity) AS TotalRevenue'),
('FROM InvoiceLine il'),
('INNER JOIN Track t'),
('ON il.TrackId = t.TrackId'),
('GROUP BY t.Name'),
('ORDER BY TotalRevenue DESC;'),
('-------------------------queryn 4------------------------------'),
('SELECT'),
('ar.Name AS Category'),
('SUM(il.UnitPrice * il.Quantity) AS CategoryRevenue'),
('FROM InvoiceLine il'),
('INNER JOIN Track t ON il.TrackId = t.TrackId'),
('INNER JOIN Album al ON t.AlbumId = al.AlbumId'),
('INNER JOIN Artist ar ON al.ArtistId = ar.ArtistId'),
('GROUP BY ar.Name'),
('ORDER BY CategoryRevenue DESC;'),
('-----------------------------query 5--------------------------'),
('SELECT'),
('i.InvoiceId'),
('i.InvoiceDate'),
('i.BillingCountry'),
('i.Total'),
('FROM Invoice i'),
('WHERE i.BillingCountry = ''USA'''),
('AND i.InvoiceDate BETWEEN ''2010-01-01'' AND ''2012-12-31'';');
